### ISSUE TITLE
RuntimeError of CUDA error

### ISSUE THREAD

**Issue by Charlie0257** [LTL2Action/LTL2Action#1]
Sorry to disturb you :P
When I run the code about the **_MiniGrid (toy experiment)_**
`python train_agent.py --algo ppo --env Adversarial-v0 --ltl-sampler Adversarial --frames-per-proc 1024 --discount 0.96 --log-interval 1 --save-interval 50 --frames 3000000`

There are the output of the code and corresponding error informaton:
```
Using backend: pytorch
train_agent.py --algo ppo --env Adversarial-v0 --ltl-sampler Adversarial --frames-per-proc 1024 --discount 0.96 --log-interval 1 --save-interval 50 --frames 3000000

Namespace(algo='ppo', batch_size=256, checkpoint_dir=None, clip_eps=0.2, discount=0.96, dumb_ac=False, entropy_coef=0.01, env='Adversarial-v0', epochs=4, eval=False, eval_env=None, eval_episodes=5, eval_procs=1, frames=3000000, frames_per_proc=1024, freeze_ltl=False, gae_lambda=0.95, gnn='RGCN_8x32_ROOT_SHARED', ignoreLTL=False, int_reward=0.0, log_interval=1, lr=0.0003, ltl_sampler='Adversarial', ltl_samplers_eval=None, max_grad_norm=0.5, model=None, noLTL=False, optim_alpha=0.99, optim_eps=1e-08, pretrained_gnn=False, procs=16, progression_mode='full', recurrence=1, save_interval=50, seed=1, value_loss_coef=0.5)

Device: cuda

Environments loaded

Training status loaded.

Observations preprocessor loaded.

GNN Number of parameters: 10016
embedding size: 64
Model loaded.

ACModel(
  (env_model): MinigridEnvModel(
    (image_conv): Sequential(
      (0): Conv2d(3, 16, kernel_size=(2, 2), stride=(1, 1))
      (1): ReLU()
      (2): MaxPool2d(kernel_size=(2, 2), stride=(2, 2), padding=0, dilation=1, ceil_mode=False)
      (3): Conv2d(16, 32, kernel_size=(2, 2), stride=(1, 1))
      (4): ReLU()
      (5): Conv2d(32, 64, kernel_size=(2, 2), stride=(1, 1))
      (6): ReLU()
    )
  )
  (gnn): RGCNRootShared(
    (linear_in): Linear(in_features=22, out_features=32, bias=True)
    (conv): RelGraphConv(
      (dropout): Dropout(p=0.0, inplace=False)
    )
    (g_embed): Linear(in_features=32, out_features=32, bias=True)
  )
  (actor): PolicyNetwork(
    (enc_): Sequential(
      (0): Sequential(
        (0): Linear(in_features=96, out_features=64, bias=True)
        (1): ReLU()
      )
      (1): Sequential(
        (0): Linear(in_features=64, out_features=64, bias=True)
        (1): ReLU()
      )
      (2): Sequential(
        (0): Linear(in_features=64, out_features=64, bias=True)
        (1): ReLU()
      )
    )
    (discrete_): Sequential(
      (0): Linear(in_features=64, out_features=7, bias=True)
    )
  )
  (critic): Sequential(
    (0): Linear(in_features=96, out_features=64, bias=True)
    (1): Tanh()
    (2): Linear(in_features=64, out_features=64, bias=True)
    (3): Tanh()
    (4): Linear(in_features=64, out_features=1, bias=True)
  )
)

Optimizer loaded.

Traceback (most recent call last):
  File "train_agent.py", line 274, in <module>
    exps, logs1 = algo.collect_experiences()
  File "/home/charlie/PycharmProjects/LTL2Action/src/torch_ac/algos/base.py", line 138, in collect_experiences
    dist, value = self.acmodel(preprocessed_obs)
  File "/home/charlie/anaconda3/envs/ltl2action/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/charlie/PycharmProjects/LTL2Action/src/model.py", line 126, in forward
    embed_gnn = self.gnn(obs.text)
  File "/home/charlie/anaconda3/envs/ltl2action/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/charlie/PycharmProjects/LTL2Action/src/gnns/graphs/RGCN.py", line 80, in forward
    h_0 = self.linear_in(g.ndata["feat"].float().squeeze())
  File "/home/charlie/anaconda3/envs/ltl2action/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/charlie/anaconda3/envs/ltl2action/lib/python3.6/site-packages/torch/nn/modules/linear.py", line 87, in forward
    return F.linear(input, self.weight, self.bias)
  File "/home/charlie/anaconda3/envs/ltl2action/lib/python3.6/site-packages/torch/nn/functional.py", line 1610, in linear
    ret = torch.addmm(bias, input, weight.t())
RuntimeError: CUDA error: CUBLAS_STATUS_EXECUTION_FAILED when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
Exception ignored in: <bound method ParallelEnv.__del__ of <torch_ac.utils.penv.ParallelEnv object at 0x7f7586573908>>
Traceback (most recent call last):
  File "/home/charlie/PycharmProjects/LTL2Action/src/torch_ac/utils/penv.py", line 41, in __del__
  File "/home/charlie/anaconda3/envs/ltl2action/lib/python3.6/multiprocessing/connection.py", line 206, in send
  File "/home/charlie/anaconda3/envs/ltl2action/lib/python3.6/multiprocessing/connection.py", line 404, in _send_bytes
  File "/home/charlie/anaconda3/envs/ltl2action/lib/python3.6/multiprocessing/connection.py", line 368, in _send
BrokenPipeError: [Errno 32] Broken pipe
```
After reading the error information, maybe there is a cuda version error in something.
But I do not found any `cudatoolkit` version information in `requirements.txt` :(

Could you tell me the cudatoolkit version information ?

**Comment by githubLeoliu** [comment]
Hi, did you solve the problem? which cuda version it should be ?
